version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=spring
      - POSTGRES_USER=spring
      - POSTGRES_PASSWORD=spring
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - springdemo
networks:
  springdemo:

volumes:
  pgdata:
    name: "spring-pgdata"

