version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=spring
      - POSTGRES_USER=spring
      - POSTGRES_PASSWORD=spring
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - springdemo
#  app:
#    image: aj/httpinterface-demo-server
#    depends_on:
#      - db
#    ports:
#      - "9092:9092"
#    networks:
#      - springdemo
#    environment:
#      - SPRING_DATASOURCE_HIKARI_JDBC_URL=jdbc:postgresql//db:5432/spring
#      - SPRING_JPA_GENERATE_DDL=true
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
networks:
  springdemo:

volumes:
  pgdata:
    name: "spring-pgdata"
